# Change these first
owner: RosenAdvertising
repo: upptime

# Prevent automatic updates
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipTemplate: true

# List of sites to monitor
sites:
  - name: Asia Pro Golf Frontend
    url: https://asiaprogolf.netlify.app/
    method: GET
    expectedStatusCodes:
      - 200
      - 304
    maxResponseTime: 5000
    assignees:
      - tobyrosen
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

  - name: Asia Pro Golf API
    url: https://asia-pro-golf-backend.onrender.com/
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    assignees:
      - tobyrosen
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      - "Accept: application/json"

  - name: API Health Check
    url: https://asia-pro-golf-backend.onrender.com/api/health
    method: GET
    expectedStatusCodes:
      - 200
      - 404  # Temporarily allow 404
    maxResponseTime: 5000
    assignees:
      - tobyrosen
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      - "Accept: application/json"

# Status website configuration
status-website:
  baseUrl: /upptime
  name: Asia Pro Golf Status
  logoUrl: https://raw.githubusercontent.com/RosenAdvertising/asia-pro-golf-frontend/main/public/images/logo.png
  theme: light
  introTitle: "**Asia Pro Golf System Status**"
  introMessage: Real-time uptime monitoring and status page for all Asia Pro Golf services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Asia Pro Golf
      href: https://asiaprogolf.netlify.app

# Notifications
notifications:
  - type: telegram
    channel: apg-status
    bot-token: "$TELEGRAM_BOT_TOKEN"
    chat-id: "$TELEGRAM_CHAT_ID"
    notification-template: |
      ⚠️ *$SITE_NAME* is $STATUS
      Response time: $RESPONSE_TIME ms
      Details: $DETAILS
    send-on-error: true
    send-on-startup: true
    send-on-statuses:
      - down
      - up
      - degraded

# Upper limits in ms after which response is considered degraded (50th percentile) or down (90th percentile)
commitMessages:
  readmeContent: ":pencil: Update summary in README"
  summaryJson: ":card_file_box: Update status summary"
  statusChange: ":arrow_up: $SITE_NAME is $STATUS"
  graphsUpdate: ":bento: Update graphs"

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  degradedPerformance: Degraded Performance
  completeOutage: Complete Outage
  partialOutage: Partial Outage

# Check interval (1 minute for testing)
heartbeatInterval: 1

# Issue settings
issues:
  open: true
  assignees: [tobyrosen]
  labels: ["bug", "outage"]

# Extra settings
uptime:
  graphs: true
  timezone: "Asia/Bangkok"
  silent: false
