# Change these first
owner: RosenAdvertising # Your GitHub organization
repo: upptime # The name of this repository

# List of sites to monitor
sites:
  - name: Asia Pro Golf Frontend
    url: https://asiaprogolf.netlify.app
    method: GET
    expectedStatusCodes:
      - 200
      - 304
    maxResponseTime: 5000
    assignees:
      - tobyrosen
    headers:
      - "User-Agent: Upptime Bot"

  - name: Asia Pro Golf API
    url: https://asia-pro-golf-backend.onrender.com/healthz
    method: GET
    expectedStatusCodes:
      - 200
    maxResponseTime: 10000
    assignees:
      - tobyrosen
    headers:
      - "User-Agent: Upptime Bot"

  - name: Render Database
    url: dpg-cufl91dds78s73fm7jqg-a # Replace with your actual Render PostgreSQL database hostname
    port: 5432
    check: "tcp-ping"
    ipv6: true

# Status website configuration
status-website:
  theme: dark
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/RosenAdvertising/asia-pro-golf-frontend/main/public/images/logo.png
  name: Asia Pro Golf Status
  introTitle: "**Asia Pro Golf System Status**"
  introMessage: Real-time uptime monitoring and status page for all Asia Pro Golf services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Asia Pro Golf
      href: https://asiaprogolf.netlify.app

# Notifications
notifications:
  - type: telegram
    channel: apg-status
    bot-token: "$TELEGRAM_BOT_TOKEN"
    chat-id: "$TELEGRAM_CHAT_ID"
    notification-template: |
      ⚠️ *$SITE_NAME* is $STATUS
      Response time: $RESPONSE_TIME ms
      Details: $DETAILS
    send-on-error: true
    send-on-startup: true
    send-on-statuses:
      - down
      - up
      - degraded

# Upper limits in ms after which response is considered degraded (50th percentile) or down (90th percentile)
commitMessages:
  readmeContent: ":pencil: Update summary in README"
  summaryJson: ":card_file_box: Update status summary"
  statusChange: ":arrow_up: $SITE_NAME is $STATUS"
  graphsUpdate: ":bento: Update graphs"

# Upptime also supports custom HTTP headers and checking specific text or JSON response
i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  degradedPerformance: Degraded Performance
  completeOutage: Complete Outage
  partialOutage: Partial Outage

# Check intervals (in minutes)
# Default: 5 minutes for GitHub Actions, 10 minutes for issues
heartbeatInterval: 5

# Issue settings (GitHub alerts for downtime)
issues:
  open: true
  assignees: [tobyrosen] # Replace with your GitHub username
  labels: ["bug", "outage"]

# Extra settings
uptime:
  graphs: true
  timezone: "Asia/Tokyo" # Set to your timezone
  silent: false
